### ISSUE TITLE
Discord.me redirect & scan failure

### ISSUE THREAD

**Issue by MattariOnline** [ordubis/RedditDSBot#5]
Discord.me redirect & scan failure

Output:
Handling submission 9hcash by KarmaEverywhere
  Link: https://discord.me/kanc
https://discord.me/kanc uses 307 to redirect to https://discord.me/
  After following redirects found final url https://discord.me/
  Ignoring; the final url was not an official link
Sleeping for 5 seconds

Notes:
The bot should also be removing the post if it redirects to a non-official link.
Non-redirected dead official links do, however, get removed.
Other redirection sites such as discord.plus and discord.st do work.

**Comment by Tjstretchalot** [comment]
This has been resolved with #7 I suggest closing
